public enum TokenType {
  
    // symbols
   LPAREN, RPAREN,
   LBRACE, RBRACE,
   LBRACKET, RBRACKET,

   COMMA, SEMICOLON, DOT,
 
   PLUS,  MINUS, ASTERISK, SLASH,

   AND, OR, NOT,

   LT, GT, EQ,

   // Literals.
   NUMBER,
   IDENT,
   STRING,

  // keywords
   WHILE, CLASS,CONSTRUCTOR,FUNCTION,
   METHOD,FIELD,STATIC,VAR,INT,
   CHAR,BOOLEAN,VOID,TRUE,FALSE,
   NULL,THIS,LET,DO,IF,ELSE, RETURN,


   EOF
}